name: Beelight-device workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:
    inputs:
      do-build-sim:
        required: true
        default: false
        type: boolean
        description: "Build for sim targets"
      do-build-emb:
        required: true
        default: true
        type: boolean
        description: "Build for embedded targets"
      extra-cmake-options:
        required: false
        default: ""
        type: string
        description: "Extra CMake options"
      retention-days:
        required: false
        default: 2
        type: number
        description: "Number of days to retain workflow run logs and artifacts"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_SIM: true
  BUILD_EMB: true
  retention-days: 2

jobs:
  build-sim:
    name: Build for simulator and unit-tests
    # if: ${{ vars.BUILD_SIM || inputs.do-build-sim }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Configure Google-test
      uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCICD_BUILD=1 ${{inputs.extra-cmake-options}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

  build-emb:
    name: Build for targets
    # if: ${{ env.BUILD_EMB || inputs.do-build-emb }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: use CMake to get lvgl (common dependency)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSIMULATOR=0 -DBUILD_TESTING=0 ${{inputs.extra-cmake-options}}

    - name: Build for SMARTRING
      run: pio run -e SMARTRING

    - name: Build for GUITION_JC3636W518
      run: pio run -e GUITION_JC3636W518

    - name: 'Upload SMARTRING Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: SMARTRING-firmware
        path: .pio/build/SMARTRING/firmware.bin
        retention-days: ${{ inputs.retention-days == '' && env.retention-days || inputs.retention-days }}

    - name: 'Upload GUITION_JC3636W518 Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: GUITION_JC3636W518-firmware
        path: .pio/build/GUITION_JC3636W518/firmware.bin
        retention-days: ${{ inputs.retention-days == '' && env.retention-days || inputs.retention-days }}
